source "https://rubygems.org"

def rails_version
  current_gemfile = File.basename(__FILE__)

  {
    "Gemfile" => nil,
    "Gemfile_rails71" => "~> 7.1.3"
  }.fetch(current_gemfile)
end

gem "rails", rails_version
gem "sqlite3"
gem "puma"
gem "webpacker"
gem "bootsnap", require: false

group :development, :test do
  gem "cypress-rails", path: ".."
end
