source "https://rubygems.org"

gem "pg"
gem "puma"
gem "shakapacker"
gem "bootsnap", require: false

group :development, :test do
  gem "cypress-rails", path: ".."
  gem "database_cleaner-active_record"
end

group :development do
  gem "appraisal"
end
