source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "~> 2.6.3"

gem "rails", "~> 6.0.0"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 3.11"
gem "webpacker", "~> 4.0"
gem "bootsnap", ">= 1.4.2", require: false

group :development, :test do
  gem "cypress-rails", path: "../.."
end
