source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "rails", "~> 6.1.4"
gem "sqlite3"
gem "puma"
gem "webpacker"
gem "bootsnap", require: false

group :development, :test do
  gem "cypress-rails", path: "../.."
end
