#!/usr/bin/env bash

set -e

directory=$1

cd example/an_app
bundle
yarn install

# test a normal test run
bundle exec rake cypress:run

# test that passing options works (by printing help)
if ! bundle exec rake cypress:run RAILS_CYPRESS_CLI_OPTS="-h" | grep -q "Usage: run \[options\]"; then
  echo "Failed to pass options to cypress run"
  exit 1
fi

