#!/usr/bin/env bash

PS4='[script/test:${LINENO}] $ '
set -euo pipefail
set -x

echo "---> Installing dependencies"
bundle
cd example
bundle
yarn
cd ..

echo "---> Running root tests"
bundle exec rake

for gemfile in example/gemfiles/*.gemfile; do
  echo "---> Running example app tests against $gemfile"
  export BUNDLE_GEMFILE="$PWD/$gemfile"
  (cd example && bundle) # ensure that gemfile's lockfile is installed
  ./script/test_example_app
  unset BUNDLE_GEMFILE
done

echo "---> Job's done!"
