#!/usr/bin/env ruby

ENV["RAILS_ENV"] = "test"
require "pathname"
require Pathname.new(Dir.pwd).join("config/environment")
require "cypress-rails"

command = ARGV[0]
result = case command
when "init"
  CypressRails::Init.new.call
when "open"
  CypressRails::Open.new.call
when "run"
  CypressRails::Run.new.call
end

exit 1 if !result
exit 0
