name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0', '3.3']
        gemfile: ['Gemfile', 'Gemfile_rails71']
        exclude:
          # Rails 7.2 requires Ruby 3.1+
          - ruby-version: '3.0'
            gemfile: 'Gemfile'

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: ./script/test ${{matrix.gemfile}}
